{{- if .Values.externalSecrets.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: sample-service

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: sample-service-secret

  data:
    - secretKey: api-key
      remoteRef:
        key: sample-service
        property: api-key

{{- end }}